trigger:
  branches:
    include:
      - main  # Change this to your main branch name

pool:
  vmImage: 'windows-latest'  # Use a Windows agent for building Android apps

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Update Node.js version to 16.x
    displayName: 'Install Node.js'

- script: |
    npm install
    cd android
    gradlew clean
  displayName: 'Install dependencies and clean build'

- script: |
    cd android
    gradlew assembleDebug
  displayName: 'Build APK'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'android/app/build/outputs/apk/debug'
    artifactName: 'APKs'
    publishLocation: 'Container'
